version: "3.1"
services:
  postgresDB:
    image: postgres:latest
    secrets:
      - dbuser
      - dbpass
    environment:
      POSTGRES_USER_FILE: /run/secrets/dbuser
      POSTGRES_PASSWORD_FILE: /run/secrets/dbpass
  centOS:
    image: centos
    deploy:
      replicas: 1
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    secrets:
      - source: my-secret
secrets:
  dbuser:
    file: ./dbpass.txt
  dbpass:
    file: ./dbpass.txt
  my-secret:
    external: true
